### ISSUE TITLE
rosbag

### ISSUE THREAD

**Issue by shanyuejun** [Yaepiii/TRLO#4]
您好，能提供一下原配置文件的rosbag吗

**Comment by Yaepiii** [comment]
通过网盘分享的文件：kitti_2011_09_30_drive_0027_synced.bag
链接: https://pan.baidu.com/s/1TBEXU69PDTKoUSt2-Koang?pwd=ccjk 提取码: ccjk 
--来自百度网盘超级会员v5的分享
KITTI07

**Comment by shanyuejun** [comment]
@Yaepiii 复现成功，收获很大，感谢

**Comment by sfhkudseukkjewvtih** [comment]
@shanyuejun @Yaepiii [你好，我想请问一下我的RVIZ显示这个样子是什么问题啊？

<img width="2560" height="1600" alt="Image" src="https://github.com/user-attachments/assets/3b0606c5-f4e8-48cb-a6f9-0f5d9d0b3c3b" />
